export const site = {
  name: 'Focaccia Bansko',
  phoneDisplay: '+359 897 822 441',
  phoneHref: '+359897822441',
  email: 'focacciaexpert@abv.bg',
  instagramHandle: '@focaccia_bansko_panini',
  instagramUrl: 'https://www.instagram.com/focaccia_bansko_panini/',
  addressBg: 'ул. „Пирин“ 93, 2770 Банско',
  addressEn: '93 Pirin St., 2770 Bansko',
  mapsUrl:
    'https://www.google.com/maps/search/?api=1&query=Focaccia%20Bansko%2C%2093%20Pirin%20St%2C%20Bansko',
  mapsEmbedUrl:
    'https://www.google.com/maps?q=Focaccia%20Bansko%2C%2093%20Pirin%20St%2C%20Bansko&output=embed',
  hours: '10:00–22:00',
};

export const copy = {
  bg: {
    nav: { home: 'Начало', menu: 'Меню', taste: 'Пътят на вкуса', location: 'Локация', contacts: 'Контакти' },
    home: {
      eyebrow: 'Италиански вкус в сърцето на Банско',
      title: 'Прясна фокача всеки ден —',
      titleAccent: 'за най-вкусния сандвич в\u00A0Банско',
      intro: [
        'Фокачата за нашите сандвичи се приготвя и изпича на място всеки ден.',
        'Мека и въздушна отвътре, с хрупкава коричка — основата на всеки наш сандвич.',
      ],
      veganFriendly: 'Веган френдли',
      menuCta: 'Разгледай менюто',
      directionsCta: 'Как да стигна',
      ratingLink: 'Виж в Google Maps',
      fresh: 'Печем на място',
      italian: 'Италиански продукти',
      location: 'Кафе, вино и кроасан',
      quickFacts: [
        { icon: 'oven', path: '/taste/focaccia', title: 'Печем на място', text: 'Фокачата за нашите сандвичи се пече на място всеки ден.' },
        { icon: 'sandwich', path: '/taste', title: 'Италиански продукти', text: 'Подбрани деликатеси с автентичен произход.' },
        { icon: 'coffee', path: '/menu#dessert', title: 'Кафе, вино и кроасан', text: 'Италианско удоволствие тук и за вкъщи.' },
      ],
      sectionEyebrow: 'Какво ще намериш при нас',
      sectionTitle: 'Малко място с голям италиански вкус',
      sectionText:
        'Сандвичи с фокача, изпечена на място, висококачествени италиански салами и сирена, вино, бира, кафе и кроасан.',
      cards: [
        { icon: 'oven', path: '/taste/focaccia', title: 'Фокача, изпечена на място', text: 'Всеки ден печем фокачата, с която приготвяме нашите сандвичи.' },
        { icon: 'sandwich', path: '/taste', title: 'Салумерия', text: 'Висококачествени сирена и салами за консумация на място или у дома.' },
        { icon: 'glass', path: '/menu#drinks', title: 'Италиански напитки', text: 'Италианско вино, пенливо вино или бира — за консумация на място или в бутилка за вкъщи.' },
        { icon: 'coffee', path: '/menu#dessert', title: 'Кроасан и италианско кафе', text: 'Кроасан, изпечен на място, с италианско еспресо или капучино.' },
      ],
      visitTitle: 'Ела да опиташ',
      visitText: 'Всеки ден от 10:00 до 22:00 ч. на ул. „Пирин“ 93, Банско.',
      call: 'Обади се',
    },
    menu: {
      eyebrow: 'МЕНЮ',
      title: 'Прясна фокача и италиански напитки',
      intro:
        'Сандвичи с фокача, изпечена на място, италиански продукти и селекция от напитки. Подбрани с внимание към вкуса и произхода.',
      sandwichesLink: 'Сандвичи',
      drinksLink: 'Напитки',
      freshBread: 'С прясно изпечена фокача',
      sandwichesTitle: 'Сандвичи',
      drinksTitle: 'Напитки',
      italianSelection: 'Италианска селекция',
      priceNote: 'Всички цени са в евро и включват данъци.',
      foodNote: 'Препоръчваме храната да се консумира до 2 часа след сервиране.',
      spicy: 'Екстра пикантно',
      vegan: 'Веган',
      ctaTitle: 'Търсиш нещо конкретно?',
      ctaText: 'Обади се и ще ти кажем какво е налично днес.',
      call: 'Обади се',
      instagram: 'Виж Instagram',
      dessertTitle: 'Десерт',
      dessertName: 'Прясно изпечен кроасан',
      dessertText: 'Предлагаме го с италианско еспресо или капучино — единственият сладък финал в менюто ни.',
      dessertPrice: 'Попитай на място',
    },
    location: {
      eyebrow: 'Намери ни',
      title: 'В сърцето на Банско',
      intro: 'На ул. „Пирин“ 93 — лесно достъпно пеша от центъра и по пътя към кабинковия лифт.',
      addressLabel: 'Адрес',
      hoursLabel: 'Работно време',
      phoneLabel: 'Телефон',
      directions: 'Отвори в Google Maps',
      planTitle: 'Ориентири около Focaccia',
      planText: 'На ул. „Пирин“ 93, близо до кабинковия лифт, Ginger, PEPCO и Four Points by Sheraton.',
      planAlt: 'Схема на местоположението на Focaccia на ул. Пирин 93 в Банско',
    },
    contacts: {
      eyebrow: 'Свържи се с нас',
      title: 'Контакти',
      intro: 'За актуални предложения, наличности и въпроси — обади се или ни пиши.',
      phone: 'Телефон',
      email: 'Имейл',
      instagram: 'Instagram',
      hours: 'Работно време',
      address: 'Адрес',
      call: 'Обади се сега',
      write: 'Изпрати имейл',
    },
    footer: {
      description: 'Сандвичи с фокача, изпечена на място, италиански продукти и напитки в Банско.',
      rights: 'Всички права запазени.',
      quickLinks: 'Бързи връзки',
      contact: 'Контакти',
    },
    open: { open: 'ОТВОРЕНО', closed: 'ЗАТВОРЕНО', opensAt: 'отваря в 10:00' },
    rating: { reviews: 'отзива' },
    notFound: { title: 'Страницата не е намерена', home: 'Към началото' },
  },
  en: {
    nav: { home: 'Home', menu: 'Menu', taste: 'Taste Journey', location: 'Location', contacts: 'Contacts' },
    home: {
      eyebrow: 'Italian flavour in the heart of Bansko',
      title: 'Fresh focaccia every day —',
      titleAccent: 'for Bansko’s tastiest sandwich',
      intro: [
        'The focaccia for our sandwiches is prepared and baked on site every day.',
        'Soft and airy inside with a crisp crust — the foundation of every sandwich we make.',
      ],
      veganFriendly: 'Vegan friendly',
      menuCta: 'Explore the menu',
      directionsCta: 'Get directions',
      ratingLink: 'View on Google Maps',
      fresh: 'Baked on site',
      italian: 'Italian products',
      location: 'Coffee, wine & croissant',
      quickFacts: [
        { icon: 'oven', path: '/taste/focaccia', title: 'Baked on site', text: 'The focaccia for our sandwiches is baked on site every day.' },
        { icon: 'sandwich', path: '/taste', title: 'Italian products', text: 'Selected delicacies with authentic origin.' },
        { icon: 'coffee', path: '/menu#dessert', title: 'Coffee, wine & croissant', text: 'Italian pleasure here or to take home.' },
      ],
      sectionEyebrow: 'What you will find here',
      sectionTitle: 'A small place with a big Italian flavour',
      sectionText:
        'Sandwiches made with focaccia baked on site, high-quality Italian cured meats and cheeses, wine, beer, coffee and croissants.',
      cards: [
        { icon: 'oven', path: '/taste/focaccia', title: 'Focaccia baked on site', text: 'Every day we bake the focaccia used to prepare our sandwiches.' },
        { icon: 'sandwich', path: '/taste', title: 'Salumeria', text: 'High-quality cheeses and cured meats to enjoy here or at home.' },
        { icon: 'glass', path: '/menu#drinks', title: 'Italian drinks', text: 'Italian wine, sparkling wine or beer — enjoy it here or take a bottle home.' },
        { icon: 'coffee', path: '/menu#dessert', title: 'Croissant & Italian coffee', text: 'A croissant baked on site, served with Italian espresso or cappuccino.' },
      ],
      visitTitle: 'Come and taste',
      visitText: 'Open daily from 10:00 to 22:00 at 93 Pirin Street, Bansko.',
      call: 'Call us',
    },
    menu: {
      eyebrow: 'MENU',
      title: 'Fresh focaccia and Italian drinks',
      intro:
        'Sandwiches made with focaccia baked on site, Italian products and a curated selection of drinks. Chosen with care for flavour and origin.',
      sandwichesLink: 'Sandwiches',
      drinksLink: 'Drinks',
      freshBread: 'Made with freshly baked focaccia',
      sandwichesTitle: 'Sandwiches',
      drinksTitle: 'Drinks',
      italianSelection: 'Italian selection',
      priceNote: 'All prices are in EUR and include taxes.',
      foodNote: 'Best consumed within 2 hours of serving.',
      spicy: 'Extra spicy',
      vegan: 'Vegan',
      ctaTitle: 'Looking for something specific?',
      ctaText: 'Call us and we will tell you what is available today.',
      call: 'Call us',
      instagram: 'View Instagram',
      dessertTitle: 'Dessert',
      dessertName: 'Freshly baked croissant',
      dessertText: 'Served with Italian espresso or cappuccino — the single sweet finish on our menu.',
      dessertPrice: 'Ask in store',
    },
    location: {
      eyebrow: 'Find us',
      title: 'In the heart of Bansko',
      intro: 'At 93 Pirin Street — an easy walk from the centre and on the way to the gondola lift.',
      addressLabel: 'Address',
      hoursLabel: 'Opening hours',
      phoneLabel: 'Phone',
      directions: 'Open in Google Maps',
      planTitle: 'Landmarks near Focaccia',
      planText: 'At 93 Pirin Street, near the gondola station, Ginger, PEPCO and Four Points by Sheraton.',
      planAlt: 'Location diagram for Focaccia at 93 Pirin Street in Bansko',
    },
    contacts: {
      eyebrow: 'Get in touch',
      title: 'Contacts',
      intro: 'For current offers, availability and questions — call or write to us.',
      phone: 'Phone',
      email: 'Email',
      instagram: 'Instagram',
      hours: 'Opening hours',
      address: 'Address',
      call: 'Call now',
      write: 'Send an email',
    },
    footer: {
      description: 'Sandwiches made with focaccia baked on site, Italian products and drinks in Bansko.',
      rights: 'All rights reserved.',
      quickLinks: 'Quick links',
      contact: 'Contact',
    },
    open: { open: 'OPEN', closed: 'CLOSED', opensAt: 'opens at 10:00' },
    rating: { reviews: 'reviews' },
    notFound: { title: 'Page not found', home: 'Back to home' },
  },
};
