export const site = {
  name: 'Focaccia Bansko',
  phoneDisplay: '+359 897 822 441',
  phoneHref: '+359897822441',
  email: 'focacciaexpert@abv.bg',
  instagramHandle: '@focaccia_bansko_panini',
  instagramUrl: 'https://www.instagram.com/focaccia_bansko_panini/',
  addressBg: 'ул. „Пирин“ 93, 2770 Банско',
  addressEn: '93 Pirin St., 2770 Bansko',
  mapsUrl:
    'https://www.google.com/maps/search/?api=1&query=Focaccia%20Bansko%2C%2093%20Pirin%20St%2C%20Bansko',
  mapsEmbedUrl:
    'https://www.google.com/maps?q=Focaccia%20Bansko%2C%2093%20Pirin%20St%2C%20Bansko&output=embed',
  hours: '10:00–22:00',
};

export const copy = {
  bg: {
    nav: { home: 'Начало', menu: 'Меню', location: 'Локация', contacts: 'Контакти' },
    home: {
      eyebrow: 'Италиански вкус в сърцето на Банско',
      title: 'Фокача, изпечена на място.',
      titleAccent: 'Всеки ден.',
      intro:
        'Прясна фокача, панини и селекция от италиански салами, сирена и напитки — на няколко крачки от центъра на Банско.',
      menuCta: 'Разгледай менюто',
      directionsCta: 'Как да стигна',
      ratingLink: 'Виж в Google Maps',
      fresh: 'Печем на място',
      italian: 'Италиански продукти',
      location: 'ул. „Пирин“ 93',
      sectionEyebrow: 'Какво ще намериш при нас',
      sectionTitle: 'Малко място с голям италиански вкус',
      sectionText:
        'Фокача за хапване на място или за из път, панини, подбрани салами и сирена, десерти, кафе и напитки.',
      cards: [
        { icon: 'oven', title: 'Прясно изпечено', text: 'Фокача и хляб, изпечени на място през деня.' },
        { icon: 'sandwich', title: 'Панини и фокача', text: 'Комбинации с италиански салами, сирена и свежи продукти.' },
        { icon: 'glass', title: 'Напитки и десерти', text: 'Кафе, вино, безалкохолни и нещо сладко за финал.' },
      ],
      visitTitle: 'Ела да опиташ',
      visitText: 'Всеки ден от 10:00 до 22:00 ч. на ул. „Пирин“ 93, Банско.',
      call: 'Обади се',
    },
    menu: {
      eyebrow: 'Нашето меню',
      title: 'Италиански вкус за всеки момент',
      intro:
        'Предложенията и наличностите могат да се променят. За актуални цени и днешната селекция ни се обади или ни посети.',
      categories: [
        {
          title: 'Фокача',
          description: 'Прясно изпечена на място — хрупкава отвън и мека отвътре.',
          items: ['Класическа фокача', 'Фокача с италиански продукти', 'Фокача на деня'],
        },
        {
          title: 'Панини',
          description: 'Топли сандвичи с подбрани италиански салами и сирена.',
          items: ['Панини със салам', 'Панини със сирена', 'Специално панини на деня'],
        },
        {
          title: 'Салами и сирена',
          description: 'Селекция за хапване на място или за вкъщи.',
          items: ['Италиански салами', 'Италиански сирена', 'Комбинирани плата'],
        },
        {
          title: 'Десерти и напитки',
          description: 'Кафе, безалкохолни, вино и сладки предложения.',
          items: ['Кафе', 'Безалкохолни напитки', 'Вино', 'Десерт на деня'],
        },
      ],
      ctaTitle: 'Търсиш нещо конкретно?',
      ctaText: 'Обади се и ще ти кажем какво е налично днес.',
      call: 'Обади се',
      instagram: 'Виж Instagram',
    },
    location: {
      eyebrow: 'Намери ни',
      title: 'В сърцето на Банско',
      intro: 'На ул. „Пирин“ 93 — лесно достъпно пеша от центъра и по пътя към планината.',
      addressLabel: 'Адрес',
      hoursLabel: 'Работно време',
      phoneLabel: 'Телефон',
      directions: 'Отвори в Google Maps',
    },
    contacts: {
      eyebrow: 'Свържи се с нас',
      title: 'Контакти',
      intro: 'За актуални предложения, наличности и въпроси — обади се или ни пиши.',
      phone: 'Телефон',
      email: 'Имейл',
      instagram: 'Instagram',
      hours: 'Работно време',
      address: 'Адрес',
      call: 'Обади се сега',
      write: 'Изпрати имейл',
    },
    footer: {
      description: 'Прясна фокача, панини и италиански продукти в Банско.',
      rights: 'Всички права запазени.',
      quickLinks: 'Бързи връзки',
      contact: 'Контакти',
    },
    open: { open: 'ОТВОРЕНО', closed: 'ЗАТВОРЕНО', opensAt: 'отваря в 10:00' },
    rating: { reviews: 'отзива' },
    notFound: { title: 'Страницата не е намерена', home: 'Към началото' },
  },
  en: {
    nav: { home: 'Home', menu: 'Menu', location: 'Location', contacts: 'Contacts' },
    home: {
      eyebrow: 'Italian flavour in the heart of Bansko',
      title: 'Focaccia baked on site.',
      titleAccent: 'Every day.',
      intro:
        'Fresh focaccia, panini and a selection of Italian cured meats, cheeses and drinks — just a few steps from central Bansko.',
      menuCta: 'Explore the menu',
      directionsCta: 'Get directions',
      ratingLink: 'View on Google Maps',
      fresh: 'Baked on site',
      italian: 'Italian products',
      location: '93 Pirin Street',
      sectionEyebrow: 'What you will find here',
      sectionTitle: 'A small place with a big Italian flavour',
      sectionText:
        'Focaccia to enjoy here or take away, panini, selected cured meats and cheeses, desserts, coffee and drinks.',
      cards: [
        { icon: 'oven', title: 'Freshly baked', text: 'Focaccia and bread baked on site throughout the day.' },
        { icon: 'sandwich', title: 'Panini & focaccia', text: 'Combinations with Italian cured meats, cheeses and fresh ingredients.' },
        { icon: 'glass', title: 'Drinks & desserts', text: 'Coffee, wine, soft drinks and something sweet to finish.' },
      ],
      visitTitle: 'Come and taste',
      visitText: 'Open daily from 10:00 to 22:00 at 93 Pirin Street, Bansko.',
      call: 'Call us',
    },
    menu: {
      eyebrow: 'Our menu',
      title: 'Italian flavour for every moment',
      intro:
        'Items and availability may change. Call or visit us for current prices and today’s selection.',
      categories: [
        {
          title: 'Focaccia',
          description: 'Freshly baked on site — crisp on the outside and soft inside.',
          items: ['Classic focaccia', 'Focaccia with Italian ingredients', 'Focaccia of the day'],
        },
        {
          title: 'Panini',
          description: 'Warm sandwiches with selected Italian cured meats and cheeses.',
          items: ['Panini with cured meats', 'Panini with cheese', 'Special panini of the day'],
        },
        {
          title: 'Cured meats & cheese',
          description: 'A selection to enjoy here or take home.',
          items: ['Italian cured meats', 'Italian cheeses', 'Mixed platters'],
        },
        {
          title: 'Desserts & drinks',
          description: 'Coffee, soft drinks, wine and sweet treats.',
          items: ['Coffee', 'Soft drinks', 'Wine', 'Dessert of the day'],
        },
      ],
      ctaTitle: 'Looking for something specific?',
      ctaText: 'Call us and we will tell you what is available today.',
      call: 'Call us',
      instagram: 'View Instagram',
    },
    location: {
      eyebrow: 'Find us',
      title: 'In the heart of Bansko',
      intro: 'At 93 Pirin Street — an easy walk from the centre and on the way to the mountain.',
      addressLabel: 'Address',
      hoursLabel: 'Opening hours',
      phoneLabel: 'Phone',
      directions: 'Open in Google Maps',
    },
    contacts: {
      eyebrow: 'Get in touch',
      title: 'Contacts',
      intro: 'For current offers, availability and questions — call or write to us.',
      phone: 'Phone',
      email: 'Email',
      instagram: 'Instagram',
      hours: 'Opening hours',
      address: 'Address',
      call: 'Call now',
      write: 'Send an email',
    },
    footer: {
      description: 'Fresh focaccia, panini and Italian products in Bansko.',
      rights: 'All rights reserved.',
      quickLinks: 'Quick links',
      contact: 'Contact',
    },
    open: { open: 'OPEN', closed: 'CLOSED', opensAt: 'opens at 10:00' },
    rating: { reviews: 'reviews' },
    notFound: { title: 'Page not found', home: 'Back to home' },
  },
};
