export const sandwiches = [
  {
    name: 'Mortadella',
    image: '/images/menu/mortadella.webp',
    weight: '500 g',
    price: '9.00 €',
    bg: 'Крем от пармезан, мортадела с шамфъстък, рукола, чери домати и балсамова редукция.',
    en: 'Parmesan cream, mortadella with pistachios, arugula, cherry tomatoes and balsamic reduction.',
  },
  {
    name: 'Tartufo',
    image: '/images/menu/tartufo.webp',
    weight: '500 g',
    price: '11.00 €',
    bg: 'Картофен крем с трюфел, сирене Проволоне, прошуто Кото с трюфел и сушени домати.',
    en: 'Potato cream with truffle, Provolone cheese, truffle prosciutto Cotto and dried tomatoes.',
  },
  {
    name: 'Tonno',
    image: '/images/menu/tonno.webp',
    weight: '500 g',
    price: '10.00 €',
    bg: 'Дижонска майонеза, сирене Проволоне, риба тон с лимон и пипер и микс зелени салати.',
    en: 'Dijon mayonnaise, Provolone cheese, tuna with lemon and pepper, and mixed green salads.',
  },
  {
    name: 'Gran Magro',
    image: '/images/menu/gran-magro.webp',
    weight: '400 g',
    price: '10.00 €',
    bg: 'Дижонска майонеза, салам Gran Magro, сирене Пармиджано Реджано и микс зелени салати.',
    en: 'Dijon mayonnaise, Gran Magro salami, Parmigiano Reggiano cheese and mixed green salads.',
  },
  {
    name: 'Formaggio',
    image: '/images/menu/formaggio.webp',
    weight: '450 g',
    price: '10.00 €',
    bg: 'Крем от пармезан, Проволоне, Горгонзола, Страчатела, зелени салати и червени боровинки.',
    en: 'Parmesan cream, Provolone, Gorgonzola, Stracciatella, green salads and dried cranberries.',
  },
  {
    name: 'Caciotta & Cotto',
    image: '/images/menu/caciotta-cotto.webp',
    weight: '530 g',
    price: '15.00 €',
    bg: 'Сирене Качота с трюфел, прошуто Кото, рукола, Страчатела и песто от шамфъстък.',
    en: 'Truffle Caciotta cheese, prosciutto Cotto, arugula, Stracciatella and pistachio pesto.',
  },
  {
    name: 'Vegano',
    image: '/images/menu/vegano.webp',
    weight: '450 g',
    price: '8.00 €',
    bg: 'Меланзане, кисели краставички, микс зелени салати, чери домати и доматен сос Арабиата.',
    en: 'Eggplant, pickles, mixed green salads, cherry tomatoes and Arrabbiata tomato sauce.',
  },
  {
    name: 'Porchetta',
    image: '/images/menu/porchetta.webp',
    weight: '450 g',
    price: '9.00 €',
    bg: 'Доматен сос Арабиата, печена поркета, рукола и сирене Моцарела.',
    en: 'Arrabbiata tomato sauce, roasted porchetta, arugula and mozzarella cheese.',
  },
  {
    name: 'Carolina Reaper',
    image: '/images/menu/carolina-reaper.webp',
    weight: '450 g',
    price: '9.00 €',
    spicy: true,
    bg: 'Екстра пикантен салам с Carolina Reaper, Проволоне, чери домати, кисели краставички и дижонска майонеза.',
    en: 'Extra-spicy salami with Carolina Reaper, Provolone, cherry tomatoes, pickles and Dijon mayonnaise.',
  },
  {
    name: 'Napoli',
    image: '/images/menu/napoli.webp',
    weight: '400 g',
    price: '8.00 €',
    bg: 'Доматен сос Арабиата, салам Napoli, сирене Пармиджано Реджано и рукола.',
    en: 'Arrabbiata tomato sauce, Napoli salami, Parmigiano Reggiano cheese and arugula.',
  },
  {
    name: 'Tacchino',
    image: '/images/menu/tacchino.webp',
    weight: '450 g',
    price: '10.00 €',
    bg: 'Пуешко филе, сирене Проволоне, микс зелени салати и дижонска майонеза.',
    en: 'Turkey fillet, Provolone cheese, mixed green salads and Dijon mayonnaise.',
  },
  {
    name: 'Burrata & Crudo',
    image: '/images/menu/burrata-crudo.webp',
    weight: '500 g',
    price: '12.00 €',
    bg: 'Картофен крем с трюфел, прошуто Крудо, рукола, чери домати и прясно сирене Бурата.',
    en: 'Potato cream with truffle, prosciutto Crudo, arugula, cherry tomatoes and fresh Burrata cheese.',
  },
];

export const drinkGroups = [
  {
    bgTitle: 'Бира',
    enTitle: 'Beer',
    items: [
      { name: 'Peroni', volume: '330 ml', price: '2.60 €' },
      { name: 'Peroni', volume: '660 ml', price: '4.00 €' },
      { name: 'Peroni Nastro Azzurro', volume: '330 ml', price: '4.00 €' },
      { name: 'Peroni Nastro Azzurro', volume: '620 ml', price: '5.00 €' },
      { name: 'Peroni Gran Riserva', volume: '330 ml', price: '5.00 €' },
      { name: 'Birra Moretti', volume: '330 ml', price: '2.60 €' },
      { name: 'Birra Moretti', volume: '660 ml', price: '4.00 €' },
    ],
  },
  {
    bgTitle: 'Вино',
    enTitle: 'Wine',
    items: [
      { bgName: 'Бяло, розе или червено', enName: 'White, rosé or red', volume: '180 ml', price: '3.00 €' },
      { bgName: 'Просеко', enName: 'Prosecco', volume: '150 ml', price: '5.00 €' },
    ],
  },
  {
    bgTitle: 'Аперитив',
    enTitle: 'Aperitif',
    items: [
      { name: 'Campari Soda Bitter 10% alc.', volume: '98 ml', price: '2.50 €' },
      { name: 'Aperol Spritz', volume: '300 ml', price: '7.00 €' },
      { name: 'Limoncello Spritz', volume: '300 ml', price: '7.00 €' },
      { bgName: 'Два Spritz-а', enName: 'Two Spritzes', volume: '2 × 300 ml', price: '10.00 €' },
    ],
  },
  {
    bgTitle: 'Италианско кафе',
    enTitle: 'Italian coffee',
    items: [
      { bgName: 'Еспресо', enName: 'Espresso', volume: '40 ml', price: '1.20 €' },
      { bgName: 'Капучино', enName: 'Cappuccino', volume: '220 ml', price: '2.00 €' },
      { bgName: 'Лате', enName: 'Latte', volume: '300 ml', price: '2.30 €' },
    ],
  },
  {
    bgTitle: 'Безалкохолни напитки',
    enTitle: 'Soft drinks',
    items: [
      { bgName: 'Минерална вода', enName: 'Mineral water', volume: '500 ml', price: '1.20 €' },
      { bgName: 'Сода лимон / портокал / мохито', enName: 'Soda lemon / orange / mojito', volume: '330 ml', price: '2.00 €' },
      { bgName: 'Студен чай San Benedetto', enName: 'San Benedetto iced tea', volume: '500 ml', price: '2.00 €' },
      { bgName: 'Coca-Cola кен', enName: 'Coca-Cola can', volume: '330 ml', price: '2.00 €' },
      { name: 'Coca-Cola Italiana', volume: '200 ml', price: '3.00 €' },
      { bgName: 'Естествено газирана минерална вода', enName: 'Naturally carbonated mineral water', volume: '500 ml', price: '1.50 €' },
    ],
  },
];
