export const tasteArticles = [
  {
    slug: 'caputo',
    category: 'foundation',
    region: 'Кампания · Неапол',
    regionEn: 'Campania · Naples',
    image: '/images/taste/articles/caputo-flour.jpg',
    accent: 'wheat',
    bg: {
      title: 'Caputo — брашното зад въздушната фокача',
      subtitle: 'Неаполитанска мелничарска традиция от 1924 г.',
      quote: '„Добрата структура започва с брашно, което може да понесе времето.“',
      intro: [
        'Историята на Mulino Caputo започва през 1924 г., когато братята Кармине и Паскуале Капуто основават мелница и фабрика за паста в Капуа. През 1939 г. производството се премества по-близо до Неапол — в Сан Джовани а Тедучо, където се намира и днес.',
        'Семейството постепенно се съсредоточава изцяло върху брашното и изгражда репутация сред неаполитанските пицайоли и занаятчийските пекари. През 2011 г. е придобита и втора мелница в Кампобасо, с което общият капацитет достига приблизително 630 тона смляна пшеница дневно.',
      ],
      productTitle: 'Защо брашното има значение',
      product: [
        'Caputo подбира и комбинира различни сортове пшеница, за да поддържа постоянни характеристики на брашното въпреки разликите между реколтите. Бавното и щадящо смилане цели да запази естествените качества на зърното.',
        'За нашата фокача избираме брашно, подходящо за продължителна ферментация. То помага на тестото да изгради стабилна и еластична мрежа, която задържа въздуха и създава мека, лека сърцевина.',
      ],
      whyTitle: 'Защо го използваме във Focaccia Bansko',
      why: 'Защото работим с тесто, на което даваме близо 48 часа. Нужно ни е брашно, което запазва структурата си и позволява на ферментацията да развие аромат и въздушност, без да търсим преки пътища.',
      facts: [
        ['Основана', '1924 г.'],
        ['Произход', 'Капуа и Неапол, Кампания'],
        ['Семейна традиция', 'Три поколения'],
        ['Производство', 'Две мелници'],
        ['Мащаб', 'Около 630 т смляна пшеница дневно'],
      ],
      market: 'Caputo не публикува точен дял за пазара на брашно за фокача. По-надеждно е да го представим като международно разпознаваема професионална марка, силно свързана с неаполитанското хлебарство и пица.',
      cta: 'Вижте как това брашно се превръща в нашата прясно изпечена фокача.',
    },
    en: {
      title: 'Caputo — the flour behind our airy focaccia',
      subtitle: 'Neapolitan milling tradition since 1924',
      quote: '“Great structure begins with flour that can withstand time.”',
      intro: [
        'Mulino Caputo began in 1924, when brothers Carmine and Pasquale Caputo founded a mill and pasta factory in Capua. In 1939, production moved closer to Naples, to San Giovanni a Teduccio, which remains home to the mill today.',
        'The family gradually focused entirely on flour and built its reputation among Neapolitan pizzaioli and artisan bakers. A second mill in Campobasso was acquired in 2011, bringing total milling capacity to roughly 630 tonnes of wheat per day.',
      ],
      productTitle: 'Why the flour matters',
      product: [
        'Caputo selects and blends different wheat varieties to keep flour performance consistent despite natural variations between harvests. Its slow, gentle milling process is designed to preserve the grain’s characteristics.',
        'For our focaccia, we choose flour suited to long fermentation. It helps the dough build a stable, elastic network that holds air and creates a soft, light crumb.',
      ],
      whyTitle: 'Why we use it at Focaccia Bansko',
      why: 'Our dough is given nearly 48 hours. We need flour that maintains its structure and lets fermentation develop aroma and airiness without shortcuts.',
      facts: [
        ['Founded', '1924'],
        ['Origin', 'Capua and Naples, Campania'],
        ['Family tradition', 'Three generations'],
        ['Production', 'Two mills'],
        ['Scale', 'Around 630 tonnes milled daily'],
      ],
      market: 'Caputo does not publish an exact share of the focaccia-flour market. It is more accurate to describe it as an internationally recognised professional brand with deep roots in Neapolitan baking and pizza.',
      cta: 'See how this flour becomes our freshly baked focaccia.',
    },
    sources: [
      ['Caputo — Company history', 'https://caputoflour.com/pages/company-new'],
      ['Caputo — Official website', 'https://caputoflour.com/'],
    ],
  },
  {
    slug: 'mazza', category: 'foundation', region: 'Ломбардия · Бреша', regionEn: 'Lombardy · Brescia', image: '/images/taste/articles/mazza-olive-oil.jpg', accent: 'olive',
    bg: {
      title: 'Mazza — зехтинът, който завършва фокачата', subtitle: 'Екстра върджин зехтин и италианска семейна история от 1946 г.',
      quote: '„Зехтинът не е финален щрих. Той е част от характера на фокачата.“',
      intro: [
        'Mazza Alimentari е семейна италианска компания, основана през 1946 г. С времето тя изгражда каталог от стотици продукти за професионалната кухня, ресторантьорството и търговията, а значителна част от дейността ѝ е насочена към международни пазари.',
        'Компанията посочва, че около 65% от оборота ѝ се генерира извън Италия. Това не е пазарен дял на зехтина, а показател за международния мащаб на бизнеса.',
      ],
      productTitle: 'Екстра върджин зехтинът',
      product: [
        'Официалното описание на Mazza посочва, че екстра върджин зехтинът се получава от първото пресоване на маслини, събрани при подходяща степен на зрялост.',
        'При фокачата зехтинът допринася за аромата, златистата коричка и меката вътрешност. Затова качеството му не може да бъде отделено от качеството на крайния хляб.',
      ],
      whyTitle: 'Защо го използваме', why: 'Избираме Mazza Extra Vergine, защото искаме средиземноморският аромат да присъства естествено във всяка тава. За нас компромисът със зехтина би бил компромис с фокачата.',
      facts: [['Основана', '1946 г.'], ['Седалище', 'Карпенедоло, провинция Бреша'], ['Портфолио', 'Над 260 вида продукти'], ['Международна дейност', 'Около 65% от оборота'], ['Наш продукт', 'Extra Virgin Olive Oil']],
      market: 'Не откриваме надежден публичен процент за дела на Mazza при екстра върджин зехтина. Затова използваме проверими данни за историята, продуктовия обхват и международната дейност.',
      cta: 'Опитайте аромата му във фокачата, която печем на място всеки ден.',
    },
    en: {
      title: 'Mazza — the olive oil that completes our focaccia', subtitle: 'Extra virgin olive oil and an Italian family story since 1946',
      quote: '“Olive oil is not a finishing touch. It is part of focaccia’s character.”',
      intro: ['Mazza Alimentari is a family-owned Italian company founded in 1946. Over time it has built a catalogue of hundreds of products for professional kitchens, restaurants and retail, with a substantial international business.', 'The company says around 65% of its turnover comes from outside Italy. This is an export indicator, not a share of the olive-oil market.'],
      productTitle: 'The extra virgin olive oil', product: ['Mazza’s official description says its extra virgin olive oil comes from the first pressing of olives harvested at the appropriate stage of ripeness.', 'In focaccia, olive oil contributes aroma, a golden crust and a soft interior. Its quality cannot be separated from the quality of the finished bread.'],
      whyTitle: 'Why we use it', why: 'We choose Mazza Extra Vergine because we want a natural Mediterranean aroma in every tray. Compromising on the olive oil would mean compromising on the focaccia.',
      facts: [['Founded', '1946'], ['Headquarters', 'Carpenedolo, Brescia'], ['Portfolio', 'More than 260 product types'], ['International business', 'Around 65% of turnover'], ['Our product', 'Extra Virgin Olive Oil']],
      market: 'No reliable public figure was found for Mazza’s share of the extra virgin olive-oil market, so we use verifiable facts about its history, range and international activity.', cta: 'Taste its aroma in the focaccia we bake on site every day.',
    },
    sources: [['Mazza — Company', 'https://mazzalimentari.com/en/company/'], ['Mazza — Extra Virgin Olive Oil', 'https://mazzalimentari.com/en/catalogo/oil/extravirgin-olive-oil-1lt/']],
  },
  {
    slug: 'sabelli-burrata', category: 'cheese', region: 'Марке · Асколи Пичено', regionEn: 'Marche · Ascoli Piceno', image: '/images/taste/articles/sabelli-burrata.jpg', accent: 'milk',
    bg: {
      title: 'Sabelli — кремообразното сърце на буратата', subtitle: 'Повече от век традиция в пресните италиански сирена',
      quote: '„Нежната обвивка крие сърце, което превръща всяка хапка в преживяване.“',
      intro: ['Историята на Sabelli започва през 1921 г. с малка мандра, основана от Николанджело Сабели в Бояно. По-късно семейството се установява в Асколи Пичено и развива компанията, без да прекъсва връзката с италианската традиция на пресните сирена.', 'Днес групата има шест производствени бази, над 600 служители и производство над 58 000 тона годишно според доклада ѝ за 2024 г.'],
      productTitle: 'Какво прави буратата специална', product: ['Буратата има тънка обвивка от моцарела и мек пълнеж от накъсани сиренени нишки и сметана. Контрастът между еластичната външност и кремообразния център е нейният отличителен характер.', 'В сандвича тя балансира солеността на прошутото и свежестта на руколата и доматите, без да доминира над останалите съставки.'],
      whyTitle: 'Защо избрахме Sabelli', why: 'Търсим бурата с постоянна кремообразност, чист млечен вкус и структура, която се отваря красиво в момента на сервиране.',
      facts: [['Основана', '1921 г.'], ['Основна база', 'Асколи Пичено, Марке'], ['Производствени бази', '6'], ['Производство през 2024 г.', '58 023 тона'], ['Пазарна позиция', 'Над 10% в общия сектор; лидер при фиксирани разфасовки бурата и страчатела']],
      market: 'Sabelli официално се определя като втория по големина производител в своя сектор в Италия с дял над 10% и като лидер при фиксираните разфасовки бурата и страчатела. Компанията не публикува отделен процент само за буратата.',
      cta: 'Открийте буратата Sabelli в Burrata & Crudo.',
    },
    en: {
      title: 'Sabelli — the creamy heart of burrata', subtitle: 'More than a century of fresh Italian cheese tradition', quote: '“A delicate shell hides the heart that turns every bite into an experience.”',
      intro: ['Sabelli began in 1921 with a small dairy founded by Nicolangelo Sabelli in Bojano. The family later established the business in Ascoli Piceno and expanded while maintaining its connection to Italian fresh-cheese tradition.', 'Today the group operates six production sites, employs more than 600 people and produced over 58,000 tonnes in 2024.'],
      productTitle: 'What makes burrata special', product: ['Burrata has a thin mozzarella shell filled with shredded cheese strands and cream. The contrast between its elastic exterior and creamy centre defines the experience.', 'In a sandwich it balances the saltiness of prosciutto and the freshness of arugula and tomatoes without overwhelming them.'],
      whyTitle: 'Why we chose Sabelli', why: 'We look for consistent creaminess, a clean milky flavour and a texture that opens beautifully when served.',
      facts: [['Founded', '1921'], ['Main base', 'Ascoli Piceno, Marche'], ['Production sites', '6'], ['2024 production', '58,023 tonnes'], ['Market position', 'Over 10% in the wider sector; leader in fixed-weight burrata and stracciatella']],
      market: 'Sabelli officially describes itself as Italy’s second-largest producer in its sector, with a share above 10%, and as the leader in fixed-weight burrata and stracciatella. It does not publish a separate percentage for burrata alone.', cta: 'Discover Sabelli burrata in Burrata & Crudo.',
    },
    sources: [['Sabelli Group — Sustainability Report 2024', 'https://sabelligroup.com/hubfs/PDF%20Bilanci%20di%20sostenibilit%C3%A0/Sustainability-Report-2024.pdf?hsLang=it'], ['Sabelli — Products', 'https://www.sabelli.it/']],
  },
  {
    slug: 'ignalat-stracciatella', category: 'cheese', region: 'Пулия · Ночи', regionEn: 'Puglia · Noci', image: '/images/taste/articles/ignalat-stracciatella.jpg', accent: 'cream',
    bg: {
      title: 'Ignalat — страчателата от сърцето на Пулия', subtitle: 'Семейна мандра, която пренася местната традиция по света', quote: '„Страчателата е кремообразното сърце на буратата — проста идея с изключително богат вкус.“',
      intro: ['Caseificio Ignalat е основана през 1948 г. в Ночи, Пулия, като малка занаятчийска мандра. Компанията запазва местната сиренарска идентичност, докато постепенно се развива на национални и международни пазари.', 'Днес Ignalat работи в над 20 държави, а износът формира около 55% от оборота ѝ. Бурата и страчателата са сред продуктите, които движат този международен растеж.'],
      productTitle: 'Какво представлява страчателата', product: ['Тя се състои от фино накъсани нишки прясна моцарела, смесени със сметана. Името идва от италианското stracciare — „накъсвам“.', 'Текстурата е нежна и кремообразна, а вкусът — млечен и деликатен. Това я прави подходяща както за бурата, така и като самостоятелен акцент в сандвичи и предястия.'],
      whyTitle: 'Защо избрахме Ignalat', why: 'Заради връзката с Пулия, специализацията в пресните сирена и постоянната кремообразност, която дава мекота и богатство на нашите комбинации.',
      facts: [['Основана', '1948 г.'], ['Произход', 'Ночи, Пулия'], ['Международно присъствие', 'Над 20 държави'], ['Износ', 'Около 55% от оборота'], ['Емблематични продукти', 'Бурата и страчатела']],
      market: 'Ignalat не публикува точен процентен дял при страчателата. Международното присъствие и делът на износа са по-надеждните показатели за мащаба на компанията.', cta: 'Опитайте страчателата в сандвичите, в които търсим мек и кремообразен баланс.',
    },
    en: {
      title: 'Ignalat — stracciatella from the heart of Puglia', subtitle: 'A family dairy taking local tradition around the world', quote: '“Stracciatella is burrata’s creamy heart — a simple idea with remarkably rich flavour.”',
      intro: ['Caseificio Ignalat was founded in 1948 in Noci, Puglia, as a small artisan dairy. It has maintained its local cheesemaking identity while gradually expanding into national and international markets.', 'Today Ignalat operates in more than 20 countries, with exports accounting for around 55% of turnover. Burrata and stracciatella are among the products driving that growth.'],
      productTitle: 'What stracciatella is', product: ['It consists of finely shredded strands of fresh mozzarella mixed with cream. Its name comes from the Italian stracciare — “to tear”.', 'The texture is soft and creamy, while the flavour is delicate and milky, making it ideal both inside burrata and as an ingredient in its own right.'],
      whyTitle: 'Why we chose Ignalat', why: 'For its connection to Puglia, its specialisation in fresh cheeses and the consistent creaminess it brings to our combinations.',
      facts: [['Founded', '1948'], ['Origin', 'Noci, Puglia'], ['International presence', 'More than 20 countries'], ['Exports', 'Around 55% of turnover'], ['Signature products', 'Burrata and stracciatella']],
      market: 'Ignalat does not publish an exact percentage for its share of the stracciatella market. Its international presence and export ratio are more reliable measures of scale.', cta: 'Taste Ignalat stracciatella in combinations designed for a soft, creamy balance.',
    },
    sources: [['Ignalat — Company and international development', 'https://www.ignalat.com/caseificio-ignalat-amazing-puglia/?lang=en'], ['Ignalat — Official website', 'https://www.ignalat.com/?lang=en']],
  },
  {
    slug: 'fior-di-latte', category: 'cheese', region: 'Марке · Италия', regionEn: 'Marche · Italy', image: '/images/taste/articles/fior-di-latte.jpg', accent: 'milk',
    bg: {
      title: 'Fior di Latte — свежата моцарела на Sabelli', subtitle: 'Мек млечен вкус и еластична структура', quote: '„Понякога най-чистият вкус идва от най-простите съставки.“',
      intro: ['Fior di latte е традиционна моцарела, произведена от краве мляко. Името подсказва нейната свежест и деликатен млечен характер.', 'Използваният от нас продукт Fior di Dolcezza е част от портфолиото на Sabelli — група с история от 1921 г. и силна специализация в моцарела и други пресни сирена.'],
      productTitle: 'Какво я отличава', product: ['За разлика от моцарелата от биволско мляко, fior di latte има по-мек и чист вкус. Тя се топи равномерно, запазва приятна еластичност и не прикрива вкуса на колбасите и сосовете.', 'Точно тази умереност я прави важна съставка: тя свързва останалите вкусове, вместо да се състезава с тях.'],
      whyTitle: 'Защо я използваме', why: 'Търсим сирене, което да носи свежест, мекота и добър баланс при затопляне. Fior di latte изпълнява тази роля естествено.',
      facts: [['Вид', 'Прясно сирене от краве мляко'], ['Производител', 'Sabelli'], ['Марка', 'Fior di Dolcezza'], ['Характер', 'Деликатен, млечен, еластичен'], ['Приложение', 'Сандвичи, пица и свежи ястия']],
      market: 'Пазарната позиция се отнася до Sabelli като група, а не до конкретната разфасовка Fior di Dolcezza. Sabelli посочва над 10% дял в по-широкия си сектор.', cta: 'Открийте fior di latte в комбинациите, където търсим мекота и чист млечен вкус.',
    },
    en: {
      title: 'Fior di Latte — Sabelli’s fresh mozzarella', subtitle: 'A gentle milky flavour and elastic texture', quote: '“Sometimes the purest flavour comes from the simplest ingredients.”',
      intro: ['Fior di latte is traditional mozzarella made from cow’s milk. Its name reflects its freshness and delicate dairy character.', 'The Fior di Dolcezza product we use belongs to Sabelli, a group founded in 1921 with strong expertise in mozzarella and other fresh cheeses.'],
      productTitle: 'What makes it different', product: ['Compared with buffalo mozzarella, fior di latte has a gentler, cleaner taste. It melts evenly, remains pleasantly elastic and does not hide the flavour of cured meats or sauces.', 'That restraint makes it important: it connects the other flavours instead of competing with them.'],
      whyTitle: 'Why we use it', why: 'We want a cheese that adds freshness, softness and balance when warmed. Fior di latte performs that role naturally.',
      facts: [['Type', 'Fresh cow’s-milk cheese'], ['Producer', 'Sabelli'], ['Brand', 'Fior di Dolcezza'], ['Character', 'Delicate, milky, elastic'], ['Uses', 'Sandwiches, pizza and fresh dishes']],
      market: 'Market-position data refer to the Sabelli group, not this specific Fior di Dolcezza pack. Sabelli reports a share above 10% in its wider sector.', cta: 'Discover fior di latte in combinations designed for softness and a clean dairy flavour.',
    },
    sources: [['Sabelli — Official website', 'https://www.sabelli.it/'], ['Sabelli Group — Sustainability Report 2024', 'https://sabelligroup.com/hubfs/PDF%20Bilanci%20di%20sostenibilit%C3%A0/Sustainability-Report-2024.pdf?hsLang=it']],
  },
  {
    slug: 'igor-gorgonzola', category: 'cheese', region: 'Пиемонт · Новара', regionEn: 'Piedmont · Novara', image: '/images/taste/articles/igor-gorgonzola.jpg', accent: 'bluecheese',
    bg: {
      title: 'IGOR — четири поколения горгонзола', subtitle: 'Традиция от Новара, подкрепена от съвременна технология', quote: '„Иновацията има смисъл, когато пази традицията, а не когато я заменя.“',
      intro: ['IGOR започва през 1935 г., когато Натале Леонарди основава малко производство в Мецомерико, край Новара. Днес четвъртото поколение на семейството продължава да развива компанията.', 'Производството съчетава традиционни мандри с модерни системи за проследимост и контрол. Компанията произвежда около 2,6 милиона пити горгонзола годишно.'],
      productTitle: 'Горгонзола — характер в малко количество', product: ['Горгонзолата е защитено италианско синьо сирене с кремообразна текстура и характерни жилки. В зависимост от вида може да бъде по-мека и сладка или по-изразена и пикантна.', 'В нашите комбинации я използваме внимателно — достатъчно, за да добави дълбочина, без да заглушава останалите сирена и свежите съставки.'],
      whyTitle: 'Защо избрахме IGOR', why: 'Заради постоянството, ясния произход и специализацията само в една от най-разпознаваемите италиански категории сирене.',
      facts: [['Основана', '1935 г.'], ['Произход', 'Новара, Пиемонт'], ['Поколения', '4'], ['Годишно производство', 'Около 2,6 млн. пити'], ['Глобален дял', '49% според компанията'], ['Износ', '52%']],
      market: 'IGOR публикува 49% глобален пазарен дял при горгонзолата и 52% дял на износа — едни от малкото конкретни и официално посочени пазарни данни в нашата селекция.', cta: 'Опитайте горгонзолата IGOR във Formaggio — нашата комбинация от италиански сирена.',
    },
    en: {
      title: 'IGOR — four generations of Gorgonzola', subtitle: 'Novara tradition supported by modern technology', quote: '“Innovation matters when it protects tradition rather than replacing it.”',
      intro: ['IGOR began in 1935, when Natale Leonardi founded a small dairy in Mezzomerico near Novara. Today the fourth generation of the family continues to develop the company.', 'Production combines traditional dairies with modern traceability and control systems. The company produces around 2.6 million Gorgonzola wheels each year.'],
      productTitle: 'Gorgonzola — character in a small amount', product: ['Gorgonzola is a protected Italian blue cheese with a creamy texture and distinctive veins. Depending on the type, it may be sweet and soft or more intense and piquant.', 'We use it carefully — enough to bring depth without overwhelming the other cheeses and fresh ingredients.'],
      whyTitle: 'Why we chose IGOR', why: 'For consistency, clear origin and deep specialisation in one of Italy’s most recognisable cheese categories.',
      facts: [['Founded', '1935'], ['Origin', 'Novara, Piedmont'], ['Generations', '4'], ['Annual production', 'Around 2.6 million wheels'], ['Global share', '49% according to the company'], ['Exports', '52%']],
      market: 'IGOR publishes a 49% global Gorgonzola market share and a 52% export share — among the clearest official market figures in our selection.', cta: 'Taste IGOR Gorgonzola in Formaggio, our Italian cheese combination.',
    },
    sources: [['IGOR — Company', 'https://www.igorgorgonzola.com/en/company/'], ['IGOR — Official website', 'https://www.igorgorgonzola.com/en/']],
  },
  {
    slug: 'trevalli-tartufo', category: 'cheese', region: 'Марке · Мачерата', regionEn: 'Marche · Macerata', image: '/images/taste/articles/trevalli-tartufo.jpg', accent: 'truffle',
    bg: {
      title: 'Trevalli — сирене с летен трюфел', subtitle: 'Кооперативна традиция от Марке и вкус на подземна гора', quote: '„Трюфелът не трябва да прикрива сиренето — той трябва да го разкрива.“',
      intro: ['Историята на Trevalli започва през 1960 г. в Мачерата. Името на марката е вдъхновено от долините на реките Езино, Потенца и Киенти и показва връзката с област Марке.', 'През следващите десетилетия компанията се развива като кооперативна система, обединяваща мандри и земеделски производители от различни италиански региони.'],
      productTitle: 'I Tipici Tartufo', product: ['Това е кремообразно смесено сирене от краве и овче мляко, произведено в Италия, с минимум 2% летен трюфел Tuber aestivum. Официалната рецептура е без консерванти.', 'Трюфелът добавя земни и горски нотки, а меката структура помага ароматът да се разпредели равномерно във всяка хапка.'],
      whyTitle: 'Защо го използваме', why: 'В Tartufo търсим ясно разпознаваем трюфелен аромат, но и истинска сиренена основа. Trevalli дава този баланс.',
      facts: [['Начало на историята', '1960 г.'], ['Произход', 'Мачерата, Марке'], ['Тип', 'Краве и овче мляко'], ['Трюфел', 'Минимум 2% Tuber aestivum'], ['Консерванти', 'Без добавени консерванти']],
      market: 'Trevalli не публикува отделен пазарен дял за I Tipici Tartufo. Силата на продукта е в проверимата рецептура и връзката с кооперативната млечна традиция на Марке.', cta: 'Опитайте го в Tartufo — с прошуто кото с трюфел и сушени домати.',
    },
    en: {
      title: 'Trevalli — cheese with summer truffle', subtitle: 'Cooperative tradition from Marche and the aroma of the forest floor', quote: '“Truffle should not hide the cheese — it should reveal it.”',
      intro: ['Trevalli’s story began in Macerata in 1960. The brand name refers to the valleys of the Esino, Potenza and Chienti rivers, reflecting its bond with the Marche region.', 'Over the following decades, the business developed as a cooperative system bringing together dairies and agricultural producers from several Italian regions.'],
      productTitle: 'I Tipici Tartufo', product: ['This creamy mixed-milk cheese is made from cow’s and sheep’s milk in Italy and contains at least 2% summer truffle, Tuber aestivum. The official recipe contains no preservatives.', 'Truffle adds earthy woodland notes while the soft texture distributes its aroma evenly through each bite.'],
      whyTitle: 'Why we use it', why: 'In Tartufo we want a clearly recognisable truffle aroma supported by a genuine cheese base. Trevalli provides that balance.',
      facts: [['Story begins', '1960'], ['Origin', 'Macerata, Marche'], ['Milk', 'Cow’s and sheep’s'], ['Truffle', 'At least 2% Tuber aestivum'], ['Preservatives', 'None added']],
      market: 'Trevalli does not publish a separate market share for I Tipici Tartufo. The product’s strength lies in its verifiable recipe and its link to Marche’s cooperative dairy tradition.', cta: 'Taste it in Tartufo with truffle prosciutto cotto and sun-dried tomatoes.',
    },
    sources: [['Trevalli — Our history', 'https://www.trevalli.cooperlat.it/en/our-history/'], ['Trevalli — I Tipici Tartufo', 'https://www.trevalli.cooperlat.it/trevalli/formaggi-stagionati/i-tipici-tartufo/']],
  },
  {
    slug: 'parmigiano-reggiano', category: 'cheese', region: 'Емилия-Романя', regionEn: 'Emilia-Romagna', image: '/images/taste/articles/parmigiano-reggiano.jpg', accent: 'aged',
    bg: {
      title: 'Parmigiano Reggiano — вкус, защитен от произхода', subtitle: 'Мляко, сол, сирище и минимум 12 месеца време', quote: '„Някои продукти не принадлежат на една марка, а на цяла земя и традиция.“',
      intro: ['Parmigiano Reggiano не е име на една компания, а защитено наименование за сирене, което може да се произвежда само в определена зона: провинциите Парма, Реджо Емилия, Модена, части от Болоня и Мантуа.', 'Всички етапи — от отглеждането на животните до производството и разфасоването — трябва да се извършват в тази зона и да следват правилата на консорциума.'],
      productTitle: 'Само три съставки', product: ['Истинското Parmigiano Reggiano се прави от мляко, сол и сирище — без добавки и консерванти. Минималното зреене е 12 месеца, а много пити достигат 24, 36 или повече месеца.', 'В първите часове всяка пита получава маркировки за произход и уникален код за проследимост. След 12-ия месец тя преминава качествена проверка, преди да получи окончателния печат.'],
      whyTitle: 'Защо го използваме', why: 'Неговият концентриран умами вкус ни позволява да добавим дълбочина с малко количество. Той работи едновременно като сирене, подправка и финален аромат.',
      facts: [['Статут', 'PDO / DOP'], ['Съставки', 'Мляко, сол и сирище'], ['Минимално зреене', '12 месеца'], ['Производство през 2024 г.', '4 079 248 пити'], ['Контрол', 'Всяка пита се инспектира и маркира']],
      market: 'Тук няма отделна фирма с пазарен дял. Това е колективно защитено производство от множество мандри под надзора на Consorzio del Formaggio Parmigiano Reggiano.', cta: 'Открийте Parmigiano Reggiano в Mortadella, Gran Magro и Napoli.',
    },
    en: {
      title: 'Parmigiano Reggiano — flavour protected by origin', subtitle: 'Milk, salt, rennet and at least 12 months of time', quote: '“Some products belong not to one brand, but to an entire land and tradition.”',
      intro: ['Parmigiano Reggiano is not the name of a single company but a protected designation for cheese made only in a defined area: Parma, Reggio Emilia, Modena and parts of Bologna and Mantua.', 'Every stage, from animal farming to cheesemaking and portioning, must take place within this area and follow the Consortium’s rules.'],
      productTitle: 'Only three ingredients', product: ['Authentic Parmigiano Reggiano is made from milk, salt and rennet, without additives or preservatives. Minimum ageing is 12 months, while many wheels mature for 24, 36 months or longer.', 'Each wheel receives origin marks and a unique traceability code in its first hours. After 12 months it undergoes quality inspection before receiving the final brand.'],
      whyTitle: 'Why we use it', why: 'Its concentrated umami flavour adds depth in a small amount. It works at once as cheese, seasoning and finishing aroma.',
      facts: [['Status', 'PDO / DOP'], ['Ingredients', 'Milk, salt and rennet'], ['Minimum ageing', '12 months'], ['2024 production', '4,079,248 wheels'], ['Control', 'Every wheel inspected and marked']],
      market: 'There is no single company market share here. Parmigiano Reggiano is a collectively protected production made by many dairies under the supervision of the official Consortium.', cta: 'Discover Parmigiano Reggiano in Mortadella, Gran Magro and Napoli.',
    },
    sources: [['Parmigiano Reggiano — FAQ', 'https://www.parmigianoreggiano.com/en-US/faq'], ['Parmigiano Reggiano — Seals and marks', 'https://www.parmigianoreggiano.com/product-guide-seals-and-marks'], ['Sustainability Report 2024', 'https://backend.parmigianoreggiano.com/uploads/CFPR_Bil_sostenibilita_2024_web_fc48be95d5.pdf']],
  },
  {
    slug: 'agriform-provolone', category: 'cheese', region: 'Венето · Верона', regionEn: 'Veneto · Verona', image: '/images/taste/articles/agriform-provolone.jpg', accent: 'provolone',
    bg: {
      title: 'Agriform — проволоне от традицията на Венето', subtitle: 'Зреене, опит и сирена, свързани с италианските региони', quote: '„Добре узрялото сирене разказва за времето, мястото и ръцете зад него.“',
      intro: ['Agriform започва през 1980 г. като обединение на девет мандри от Венето. През 1989 г. се оформя като компания, специализирана в зреенето и продажбата на Grana Padano и други типични италиански сирена.', 'През 2021 г. сливането с Parmareggio създава Caseifici GranTerre. Agriform остава марка, свързана с качествени сирена от Венето и други италиански региони.'],
      productTitle: 'Проволоне — сирене с две лица', product: ['Проволонето е полутвърдо сирене от краве мляко и принадлежи към семейството на pasta filata — сирена с изтеглена сиренена маса.', 'В зависимост от сирището и зреенето то може да бъде по-меко и сладко или по-изразено и пикантно. В нашите сандвичи използваме неговата способност да се топи и да свързва останалите съставки.'],
      whyTitle: 'Защо избрахме Agriform', why: 'Заради опита в селекцията, зреенето и разфасоването на италиански сирена и заради постоянството, което е важно в професионалната кухня.',
      facts: [['Начало', '1980 г.'], ['Регион', 'Венето'], ['Официално Agriform', '1989 г.'], ['Капацитет за зреене', 'До 200 000 пити според историята на компанията'], ['От 2021 г.', 'Част от Caseifici GranTerre']],
      market: 'Agriform не публикува отделен процент за проволонето. Компанията се представя като водещ производител и търговец на твърди PDO сирена в по-широката си категория.', cta: 'Открийте проволоне в Tartufo, Tonno, Porchetta, Carolina Reaper и Tacchino.',
    },
    en: {
      title: 'Agriform — Provolone from Veneto tradition', subtitle: 'Ageing, expertise and cheeses connected to Italian regions', quote: '“A well-matured cheese tells the story of time, place and the hands behind it.”',
      intro: ['Agriform began in 1980 as a union of nine dairies from Veneto. In 1989 it was formally established as a company specialising in ageing and marketing Grana Padano and other traditional Italian cheeses.', 'In 2021, its merger with Parmareggio created Caseifici GranTerre. Agriform remains a brand associated with quality cheeses from Veneto and other Italian regions.'],
      productTitle: 'Provolone — a cheese with two personalities', product: ['Provolone is a semi-hard cow’s-milk cheese in the pasta filata family, made with stretched curd.', 'Depending on rennet and ageing, it may be mild and sweet or more pronounced and piquant. In our sandwiches, we value its ability to melt and connect the other ingredients.'],
      whyTitle: 'Why we chose Agriform', why: 'For its expertise in selecting, ageing and portioning Italian cheeses and for the consistency required in a professional kitchen.',
      facts: [['Beginnings', '1980'], ['Region', 'Veneto'], ['Agriform established', '1989'], ['Ageing capacity', 'Up to 200,000 wheels in the company history'], ['Since 2021', 'Part of Caseifici GranTerre']],
      market: 'Agriform does not publish a separate percentage for Provolone. It presents itself as a leading producer and marketer of hard PDO cheeses in its wider category.', cta: 'Discover Provolone in Tartufo, Tonno, Porchetta, Carolina Reaper and Tacchino.',
    },
    sources: [['Agriform — Presentation and history', 'https://www.agriform.it/en/presentation'], ['Agriform — Products', 'https://www.agriform.it/en/products']],
  },
  {
    slug: 'casa-modena', category: 'cured', region: 'Емилия-Романя · Модена', regionEn: 'Emilia-Romagna · Modena', image: '/images/taste/articles/casa-modena.jpg', accent: 'prosciutto',
    bg: {
      title: 'Casa Modena — изкуството на прошутото', subtitle: 'Прошуто кото и крудо от една от емблематичните италиански области за колбаси', quote: '„Разликата между кото и крудо е различен път към една и съща цел — чист вкус на месото.“',
      intro: ['Casa Modena е марка на GranTerre, група, която обединява италиански сирена и колбаси с ясно регионално наследство. Марката е тясно свързана с Емилия-Романя и традицията на Модена.', 'В нашите сандвичи използваме прошуто кото с трюфел и прошуто крудо — два продукта с различен характер и приложение.'],
      productTitle: 'Кото и крудо', product: ['Prosciutto cotto се приготвя чрез бавно термично обработване на свински бут. Официалният продукт „alta qualità“ на Casa Modena е без добавени полифосфати, лактоза, глутамат и глутен.', 'Prosciutto crudo се осолява и зрее, без да се готви. При Parma версията рецептата е само свински бут и морска сол, без добавки и консерванти.'],
      whyTitle: 'Защо избрахме Casa Modena', why: 'Кото носи мекота и деликатна соленост, а крудо — по-дълбок аромат от зреенето. Това ни позволява да изграждаме различни сандвичи, без да променяме стандарта за качество.',
      facts: [['Регионална връзка', 'Модена, Емилия-Романя'], ['Група', 'GranTerre'], ['Наши продукти', 'Прошуто кото с трюфел и прошуто крудо'], ['Крудо', 'Дълго зреене'], ['Кото alta qualità', 'Без добавени полифосфати']],
      market: 'Не посочваме отделен пазарен дял на Casa Modena, защото публичните групови данни не разграничават надеждно конкретните видове прошуто.', cta: 'Опитайте кото в Tartufo и Caciotta & Cotto, а крудо — в Burrata & Crudo.',
    },
    en: {
      title: 'Casa Modena — the art of prosciutto', subtitle: 'Prosciutto cotto and crudo from one of Italy’s iconic cured-meat regions', quote: '“Cotto and crudo follow different paths toward the same goal — the pure flavour of the meat.”',
      intro: ['Casa Modena is a GranTerre brand, part of a group bringing together Italian cheeses and cured meats with strong regional roots. The brand is closely connected with Emilia-Romagna and Modena’s food tradition.', 'We use truffle prosciutto cotto and prosciutto crudo — two products with very different character and uses.'],
      productTitle: 'Cotto and crudo', product: ['Prosciutto cotto is made by slowly cooking pork leg. Casa Modena’s official alta qualità product contains no added polyphosphates, lactose, glutamate or gluten.', 'Prosciutto crudo is salted and matured without cooking. The Parma version contains only pork leg and sea salt, with no additives or preservatives.'],
      whyTitle: 'Why we chose Casa Modena', why: 'Cotto brings softness and delicate salinity, while crudo adds the deeper aroma of maturation. This lets us create different sandwiches without changing our quality standard.',
      facts: [['Regional link', 'Modena, Emilia-Romagna'], ['Group', 'GranTerre'], ['Our products', 'Truffle prosciutto cotto and prosciutto crudo'], ['Crudo', 'Long maturation'], ['Cotto alta qualità', 'No added polyphosphates']],
      market: 'We do not state a separate Casa Modena market share because public group data do not reliably distinguish the individual prosciutto categories.', cta: 'Taste cotto in Tartufo and Caciotta & Cotto, and crudo in Burrata & Crudo.',
    },
    sources: [['Casa Modena — Prosciutto Cotto', 'https://casamodena-parmareggio.com/prodotto/prosciutto-cotto/'], ['Casa Modena — Prosciutto Crudo di Parma', 'https://casamodena-parmareggio.com/prodotto/prosciutto-crudo/'], ['GranTerre — Group history', 'https://www.granterre.it/it/il-gruppo/la-storia']],
  },
  {
    slug: 'coati-napoli', category: 'cured', region: 'Венето · Валполичела', regionEn: 'Veneto · Valpolicella', image: '/images/taste/articles/coati-napoli.jpg', accent: 'salami',
    bg: {
      title: 'Coati — традиционният Salame Napoli', subtitle: 'Едра структура, естествени подправки и бавно зреене', quote: '„При добрия салам времето и подправките трябва да се усещат, но месото остава в центъра.“',
      intro: ['Salumificio F.lli Coati работи в Марано ди Валполичела, близо до Верона, и се специализира в италиански колбаси, прошуто кото, панчета, speck и други месни продукти.', 'Salame Napoli от Coati следва традиционен профил с едро смилане и естествени подправки и аромати.'],
      productTitle: 'Какво отличава Salame Napoli', product: ['Това е салам с по-едра структура и ясно изразен, но балансиран аромат. Официалното описание посочва само естествени подправки и аромати.', 'Продуктът е без глутен и без млечни производни, което е важно за ясната информация към гостите.'],
      whyTitle: 'Защо го използваме', why: 'Заради традиционния профил, отчетливата текстура и способността му да запази характера си до сос арабиата, пармиджано реджано и рукола.',
      facts: [['Производител', 'Salumificio F.lli Coati'], ['Място', 'Марано ди Валполичела, Верона'], ['Структура', 'Едро смилане'], ['Овкусяване', 'Естествени подправки и аромати'], ['Алергени', 'Без глутен и млечни производни']],
      market: 'Coati не публикува точен дял при Salame Napoli. Представяме продукта чрез проверимите му характеристики, а не чрез непотвърдени класации.', cta: 'Опитайте го в Napoli със сос арабиата, Parmigiano Reggiano и рукола.',
    },
    en: {
      title: 'Coati — traditional Salame Napoli', subtitle: 'Coarse texture, natural spices and slow maturation', quote: '“In a good salami, time and seasoning should be present, but the meat remains central.”',
      intro: ['Salumificio F.lli Coati operates in Marano di Valpolicella near Verona and specialises in Italian salami, cooked hams, pancetta, speck and other cured-meat products.', 'Coati’s Salame Napoli follows a traditional profile with a coarse grain and natural spices and flavourings.'],
      productTitle: 'What distinguishes Salame Napoli', product: ['It has a coarse texture and a clear but balanced aroma. The official description specifies only natural spices and flavourings.', 'The product is gluten-free and contains no milk derivatives, useful information for guests with dietary needs.'],
      whyTitle: 'Why we use it', why: 'For its traditional profile, distinct texture and ability to retain its character alongside arrabbiata sauce, Parmigiano Reggiano and arugula.',
      facts: [['Producer', 'Salumificio F.lli Coati'], ['Place', 'Marano di Valpolicella, Verona'], ['Texture', 'Coarse grain'], ['Seasoning', 'Natural spices and flavourings'], ['Allergens', 'No gluten or milk derivatives']],
      market: 'Coati does not publish an exact share for Salame Napoli. We present the product through verified characteristics rather than unconfirmed rankings.', cta: 'Taste it in Napoli with arrabbiata sauce, Parmigiano Reggiano and arugula.',
    },
    sources: [['Coati — Salame Napoli', 'https://www.salumificiocoati.it/projects-archive/salame-napoli-diam65/'], ['Coati — Official website', 'https://www.salumificiocoati.it/']],
  },
  {
    slug: 'mangiafuoco', category: 'cured', region: 'Ломбардия · Мантуа', regionEn: 'Lombardy · Mantua', image: '/images/taste/articles/mangiafuoco.jpg', accent: 'chilli',
    bg: {
      title: 'Mangiafuoco — салам за любителите на истински люто', subtitle: 'Carolina Reaper, Trinidad Scorpion Moruga и италианско свинско месо', quote: '„Лютото има смисъл, когато носи аромат, а не само сила.“',
      intro: ['Mangiafuoco е пикантен салам на Salumi Merlotti от района на Мантуа. Компанията свързва продукта с традиционното италианско колбасарство и с внимателно контролирано зреене.', 'Рецептата използва Carolina Reaper и Trinidad Scorpion Moruga — две от най-лютите чушки в света, отглеждани в Италия чрез биологично земеделие според производителя.'],
      productTitle: 'Пикантност с ясна рецептура', product: ['Официалният състав посочва 82% чисто месо, 13% мазнина и 5% подправки, аромати и технологични помощни средства. Зреенето е 30 дни.', 'Резултатът е салам, който започва с месен и подправъчен аромат, а лютото се развива постепенно.'],
      whyTitle: 'Защо го използваме', why: 'Искаме пикантният ни сандвич да има истински характер, а не просто лютив сос. Mangiafuoco внася аромат, текстура и постепенно нарастваща сила.',
      facts: [['Производител', 'Salumi Merlotti'], ['Място', 'Мармироло, Мантуа'], ['Месо', 'Италианско свинско'], ['Люти чушки', 'Carolina Reaper и Trinidad Scorpion Moruga'], ['Зреене', '30 дни']],
      market: 'Няма публичен пазарен дял за Mangiafuoco. Това е специализиран нишов продукт, който се отличава с конкретна рецептура, а не с масов обем.', cta: 'Опитайте го в Carolina Reaper — най-пикантния сандвич в менюто ни.',
    },
    en: {
      title: 'Mangiafuoco — salami for serious heat lovers', subtitle: 'Carolina Reaper, Trinidad Scorpion Moruga and Italian pork', quote: '“Heat matters when it carries aroma, not only intensity.”',
      intro: ['Mangiafuoco is a spicy salami by Salumi Merlotti from the Mantua area. The producer connects it with traditional Italian charcuterie and carefully controlled maturation.', 'The recipe uses Carolina Reaper and Trinidad Scorpion Moruga, two of the world’s hottest chillies, grown organically in Italy according to the producer.'],
      productTitle: 'Heat with a clear recipe', product: ['The official composition lists 82% lean pork, 13% pork fat and 5% flavourings, spices and processing aids. It is matured for 30 days.', 'The result begins with meat and spice aromas, while the heat builds gradually.'],
      whyTitle: 'Why we use it', why: 'We want our spicy sandwich to have genuine character, not simply a hot sauce. Mangiafuoco brings aroma, texture and gradually rising heat.',
      facts: [['Producer', 'Salumi Merlotti'], ['Place', 'Marmirolo, Mantua'], ['Meat', 'Italian pork'], ['Chillies', 'Carolina Reaper and Trinidad Scorpion Moruga'], ['Maturation', '30 days']],
      market: 'There is no public market share for Mangiafuoco. It is a specialist niche product distinguished by its recipe rather than mass volume.', cta: 'Taste it in Carolina Reaper, the hottest sandwich on our menu.',
    },
    sources: [['Salumi Merlotti — Mangiafuoco', 'https://www.salumimerlotti.it/en/product-page/mangiafuoco'], ['Salumi Merlotti — Official website', 'https://www.salumimerlotti.it/en']],
  },
  {
    slug: 'peroni', category: 'drinks', region: 'Ломбардия / Рим', regionEn: 'Lombardy / Rome', image: '/images/taste/articles/peroni-beer.jpg', accent: 'beer',
    bg: {
      title: 'Peroni — италианска бирена история от 1846 г.', subtitle: 'От малка пивоварна във Виджевано до марка в десетки пазари', quote: '„Добрата бира не конкурира храната — тя освежава следващата хапка.“',
      intro: ['През 1846 г. Франческо Перони открива малка пивоварна във Виджевано с прилежащо заведение. Оттам започва историята на марка, която се развива заедно с индустриалната история на Италия.', 'Днес Birra Peroni е част от Asahi Group и присъства на множество международни пазари, но продължава да изгражда идентичността си около италианското наследство.'],
      productTitle: 'Лекота и свежест до фокачата', product: ['Лагерът е естествен партньор на сандвичи със сирена и колбаси: карбонизацията освежава небцето, а умерената горчивина балансира мазнината и солеността.', 'Peroni Nastro Azzurro е разработена с италианска царевица Nostrano и има сух, чист и освежаващ профил.'],
      whyTitle: 'Защо предлагаме Peroni', why: 'Защото е разпознаваема италианска бира, която стои естествено до фокача, прошуто и сирена, без да доминира над храната.',
      facts: [['Основана', '1846 г.'], ['Основател', 'Франческо Перони'], ['Начало', 'Виджевано'], ['Днес', 'Част от Asahi Group'], ['Публикуван дял', '14,8% по стойност в отчет на компанията']],
      market: 'В устойчивия си отчет Birra Peroni посочва 14,8% дял по стойност за разглеждания италиански пазар. Това е групов показател, не отделен дял за конкретна бутилка.', cta: 'Изберете размера и стила Peroni, който най-добре пасва на вашия сандвич.',
    },
    en: {
      title: 'Peroni — an Italian beer story since 1846', subtitle: 'From a small brewery in Vigevano to a brand across global markets', quote: '“Good beer does not compete with food — it refreshes the next bite.”',
      intro: ['In 1846 Francesco Peroni opened a small brewery in Vigevano with an adjoining pub. This marked the beginning of a brand that grew alongside Italy’s industrial history.', 'Today Birra Peroni belongs to Asahi Group and is present in numerous international markets while continuing to build its identity around Italian heritage.'],
      productTitle: 'Lightness and freshness with focaccia', product: ['Lager is a natural partner for sandwiches with cheese and cured meats: carbonation refreshes the palate while moderate bitterness balances fat and salt.', 'Peroni Nastro Azzurro is made with Italian Nostrano maize and has a dry, clean and refreshing profile.'],
      whyTitle: 'Why we serve Peroni', why: 'It is a recognisable Italian beer that sits naturally beside focaccia, prosciutto and cheese without dominating the food.',
      facts: [['Founded', '1846'], ['Founder', 'Francesco Peroni'], ['Origin', 'Vigevano'], ['Today', 'Part of Asahi Group'], ['Published share', '14.8% by value in a company report']],
      market: 'Birra Peroni reports a 14.8% value share for the relevant Italian market in its sustainability reporting. This is a group-level indicator, not a share for one specific bottle.', cta: 'Choose the Peroni size and style that best suits your sandwich.',
    },
    sources: [['Birra Peroni — History', 'https://www.birraperoni.it/la-nostra-storia/il-racconto/'], ['Birra Peroni — Sustainability report', 'https://www.birraperoni.it/wp-content/uploads/svgs/Birra%20Peroni_Together%20we%20make%20the%20difference_Sustainable%20Development%20Report.pdf'], ['Birra Peroni — Official website', 'https://www.birraperoni.it/en/']],
  },
  {
    slug: 'caffe-corsini', category: 'drinks', region: 'Тоскана · Арецо', regionEn: 'Tuscany · Arezzo', image: '/images/taste/articles/corsini-coffee.jpg', accent: 'coffee',
    bg: {
      title: 'Caffè Corsini — тосканска култура в една чаша', subtitle: 'Печене на кафе в Арецо от 1950 г.', quote: '„Еспресото е малка напитка, но оставя дълъг финал.“',
      intro: ['Caffè Corsini започва през 1950 г. с Корсино Корсини и необичаен „вертикален магазин“ в центъра на Арецо: зелено кафе на горния етаж, печене по средата и продажба на прясно смляно кафе на приземния етаж.', 'Компанията се развива от местна пекарна за кафе до международна марка, като запазва силна връзка с Тоскана и с обучението на баристи.'],
      productTitle: 'Иновации в италианското кафе', product: ['През 1987 г. Corsini представя първото кафе в Италия, което ясно декларира произхода си върху опаковката. През 1990 г. компанията въвежда и първото италианско филтърно кафе в партньорство с Melitta.', 'През 2005 г. е създадена академия за обучение на баристи. Тази култура на кафе е важна не само за зърната, но и за начина, по който се смилат, дозират и сервират.'],
      whyTitle: 'Защо избрахме Corsini', why: 'Защото искаме еспресото и капучиното да имат ясно италианско лице — балансиран аромат, плътност и чист финал след храна или кроасан.',
      facts: [['Основана', '1950 г.'], ['Място', 'Арецо, Тоскана'], ['Първо кафе с деклариран произход в Италия', '1987 г.'], ['Академия за баристи', 'От 2005 г.'], ['Партньорство с Melitta', '70% участие от 2021 г.']],
      market: 'Corsini не публикува точен дял на пазара на еспресо. Компанията се описва като една от водещите италиански пекарни и има международно присъствие, но избягваме непотвърдени проценти.', cta: 'Завършете пътя на вкуса с италианско еспресо или капучино и кроасан, изпечен на място.',
    },
    en: {
      title: 'Caffè Corsini — Tuscan coffee culture in a cup', subtitle: 'Roasting coffee in Arezzo since 1950', quote: '“Espresso is a small drink with a long finish.”',
      intro: ['Caffè Corsini began in 1950 with Corsino Corsini and an unusual “vertical shop” in central Arezzo: green coffee stored upstairs, roasting in the middle and freshly ground coffee sold on the ground floor.', 'The business grew from a local roaster into an international brand while maintaining a strong connection to Tuscany and barista education.'],
      productTitle: 'Innovation in Italian coffee', product: ['In 1987 Corsini introduced the first coffee in Italy to clearly declare its origin on the pack. In 1990 the company also introduced Italy’s first filter coffee in partnership with Melitta.', 'A barista academy followed in 2005. This coffee culture concerns not only the beans but also how they are ground, dosed and served.'],
      whyTitle: 'Why we chose Corsini', why: 'We want espresso and cappuccino with a clear Italian identity: balanced aroma, body and a clean finish after food or a freshly baked croissant.',
      facts: [['Founded', '1950'], ['Place', 'Arezzo, Tuscany'], ['First origin-declared coffee in Italy', '1987'], ['Barista academy', 'Since 2005'], ['Melitta partnership', '70% stake since 2021']],
      market: 'Corsini does not publish an exact share of the espresso market. It describes itself as a leading Italian roaster with international presence, but we avoid unverified percentages.', cta: 'Complete the journey with an Italian espresso or cappuccino and a croissant baked on site.',
    },
    sources: [['Caffè Corsini — Our history', 'https://caffecorsini.com/en-eu/pages/our-history'], ['Caffè Corsini — Official website', 'https://caffecorsini.com/en-eu']],
  },
];

export const tasteCategories = {
  foundation: { bg: 'Основата', en: 'The foundation' },
  cheese: { bg: 'Сирената', en: 'The cheeses' },
  cured: { bg: 'Колбасите', en: 'The cured meats' },
  drinks: { bg: 'Напитките', en: 'The drinks' },
};

export function getTasteArticle(slug) {
  return tasteArticles.find((article) => article.slug === slug);
}
